### ISSUE TITLE
Logo!

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/Fritz.EpicBuildMusic#14]
This project needs a logo and icon prior to uploading to the Visual Studio Marketplace

**Comment by checkdigits** [comment]
First attempt...

As a PNG.

Also available as .ICO and .PSD  :)

![epicbuildmusicicon](https://user-images.githubusercontent.com/2126394/33902727-8c5f5ccc-df3b-11e7-9c3a-ca2ccf17ab23.png)

**Comment by checkdigits** [comment]
All versions, in a zip file...

[epicbuildmusicicon.zip]
(https://github.com/csharpfritz/Fritz.EpicBuildMusic/files/1552893/epicbuildmusicicon.zip)

**Comment by csharpfritz** [comment]
Thanks @checkdigits - I really appreciate the cool logo.  I'm rolling it out with v0.3
