### ISSUE TITLE
User-interface assistance

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/Fritz.EpicBuildMusic#15]
The user-interface for the options dialog needs some help.  It looks like there may be a high-DPI issue with the placement and scaling of the content.

If someone with an eye for user-interface design can help make it look a bit better, that would be very appreciated.

**Comment by checkdigits** [comment]
See: https://github.com/csharpfritz/Fritz.EpicBuildMusic/pull/18

**Comment by csharpfritz** [comment]
Thank you for your contribution!
