### ISSUE TITLE
Default shipping music

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/Fritz.EpicBuildMusic#8]
Challenge:  how do we distribute default music without incurring copyright issues?  https://freesound.org 

Can we deploy something like any of the following:
- [ ] Modem carrier sound

**Comment by checkdigits** [comment]
Ask and you shall receive: [https://github.com/checkdigits/build_over_dialup](https://github.com/checkdigits/build_over_dialup)  :)

All from a sound released under Creative Commons  - and I released it under the CC licence too so no licensing issues.

**Comment by csharpfritz** [comment]
Awesome stuff @checkdigits - thank you for sharing!  I'll add the mp3 to the project and add an appropriate reference for licensing.

**Comment by csharpfritz** [comment]
Added modem carrier sound to the project and added attribution to @checkdigits in the LICENSE
