### ISSUE TITLE
Concurrent Build Issues

### ISSUE THREAD

**Issue by smudge202** [csharpfritz/Fritz.EpicBuildMusic#9]
> *Sat idle having seen a tweet about upcoming stream - decided to have a scan of the code so apologies for tedious stuff*

I'm not sure if relevant, but solutions with multiple entry points or orphaned dependency trees will typically run in parallel.

Could this line cause a concurrency issue under those circumstances?

https://github.com/csharpfritz/Fritz.EpicBuildMusic/blob/master/Fritz.EpicBuildMusic/BuildMusicPackage.cs#L192

Would a [`Interlocked.Increment(ref int location)`](https://msdn.microsoft.com/en-us/library/dd78zt0c(v=vs.110).aspx) be more appropriate?

**Comment by csharpfritz** [comment]
Fixed in dev
